source 'https://rubygems.org'
ruby '1.9.3'
gem 'rails', '3.2.19'
# Rails defaults
gem 'sqlite3'
gem 'sass-rails', '>= 3.2.6'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 3.2.2'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
# learn-rails
gem 'activerecord-tableless'
gem 'compass-rails', '~> 2.0.alpha.0'
gem 'figaro'
gem 'gibbon'
gem 'google_drive'
gem 'high_voltage'
gem 'simple_form'
gem 'zurb-foundation'
group :development do 
gem 'quiet_assets'
gem 'rails_layout'
end